on: push
name: Tests
jobs:
  onMasterOrPR:
    name: On master or PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer Downloads
      uses: actions/cache@v2
      with:
        path: vendor/
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

    - uses: php-actions/composer@v4
      with:
        composer_version: 1
    - name: Lint
      run: make fmt
    - name: Test
      run: make test
    - name: Cover
      run: make cover
