on: push
name: Tests
jobs:
  onMasterOrPR:
    name: On master or PR
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v2
    - name: Set up PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install Dependencies
      run: make install
    - name: Lint
      run: make fmt
    - name: Test
      run: make test
    - name: Cover
      run: make cover
