on: push
name: Tests
jobs:
  onMasterOrPR:
    name: On master or PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v4
      with:
        composer_version: 1
    - name: Switch Composer Version
      run: switch-composer-version 1
    - name: Install Dependencies
      run: make install
    - name: Lint
      run: make fmt
    - name: Test
      run: make test
    - name: Cover
      run: make cover
