name: Tests
on: [push]
jobs:
  onMasterOrPR:
    name: On master or PR
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      uses: php-actions/composer@v4
      with:
        composer_version: 1
      run: make install
    - name: Lint
      run: make fmt
    - name: Test
      run: make test
    - name: Cover
      run: make cover
